version: "2"
services:

  consul:
    image: consul
    networks:
      - consul-network
    ports:
      - "8500:8500"

  postgres:
    image: postgres
    ports:
      - "15432:5432"
    volumes:
      - /home/gstorck/workspace/data/postgresql:/var/lib/postgresql/data
    networks:
      - consul-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - consul-network

  app:
    build: ../../
    networks:
      - consul-network
    ports:
      - "8080:8080"
    depends_on:
      - consul
      - postgres
    environment:
      - CONSUL_HOST=consul
      - CONSULT_PORT=8500
      - JDBC_URL=jdbc:postgresql://localhost/mydatabase
      - JDBC_USER=postgres
      - JDBC_PASSWORD=root
      - JDBC_DRIVER=org.postgresql.Driver

networks:

  consul-network:
    driver: bridge