micronaut:
  application:
    name: catalog-service
  config-client:
    enabled: true
  server:
    port: 8082

tracing:
  zipkin:
    http:
      url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
    enabled: true
    sampler:
      probability: 1

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"