micronaut:
  application:
    name: catalog-service
  config-client:
    enabled: true
  server:
    port: 8082

tracing:
  zipkin:
    http:
      url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
    enabled: true
    sampler:
      probability: 1

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost/mydatabase`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:root}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    packages-to-scan:
      - 'catalogservice.db.domains'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true