micronaut:
  application:
    name: catalog-service

tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"