package com.ranefare.plancatalogservice.contract.contracts

import com.ranefare.plancatalogservice.contract.domains.resources.InsuranceCoverageItemResource

interface CrudInsuranceCoverageItemContract : CrudContract<InsuranceCoverageItemResource, String>
