micronaut:
  application:
    name: plan-catalog-service
  config-client:
    enabled: true
  server:
    port: 8080

#tracing:
#  zipkin:
#    http:
#      url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
#    enabled: true
#    sampler:
#      probability: 1
#
#consul:
#  client:
#    registration:
#      enabled: true
#    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/plancatalogdb`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:root}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    packages-to-scan:
      - 'com.ranefare.plancatalogservice.db.domains'
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        hbm2ddl:
          auto: none
        show_sql: true

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.yml'